name: '${project.name}'
version: '${project.version}'
main: club.winterlegends.hubcore.HubCore
author: Invisibilities
description: '${project.description}'
website: '${project.url}'
depend:
  - ProtocolLib
  - DecentHolograms
commands:
  hubcore:
    aliases:
      - hc